name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        
        # Create a new branch called 'gh-pages' (or use an existing one for deployment)
        git checkout --orphan gh-pages
        git rm -rf .
        
        # Copy the built site from the _site folder to the root of the branch
        cp -a ${{ github.workspace }}/_site/. .
        
        # Commit the changes
        git add .
        git commit -m "Deploy Jekyll site to GitHub Pages"
        
        # Push the changes to the 'gh-pages' branch
        git push origin gh-pages --force
